nelmio_api_doc:
    documentation:
        info:
            title: KartoKloud
            description: This is an awesome app!
            version: 1.0.0
    routes: # to filter documented routes
        path_patterns:
            - ^/api/v1 # Accepts routes under /api except /api/doc
